### PR TITLE
Fixes issue #51: Changed error message in case client ID is not provided

### LINKED ISSUE #51: [BUG] Display more meaningful error message when Client ID not provided
## Bug Description

This project requires a MyAnimeList Client ID in order to fetch the required data from the API.
https://github.com/jmakhack/myanimelist-cli/blob/61f91c22a837838b138ea0c35b8c947eda66b1aa/src/mya.c#L12

When the Client ID is not provided, the following misleading error is displayed:
Screen Shot 2022-10-08 at 6 52 14 PM

## Expected Behavior

Instead of a `User not found` error message, the expected behavior is that a more meaningful error message would be displayed such as `Client ID has not been provided`.

## Environment

Operating System: Ubuntu 22.04

## Additional Context

Note: This issue is to only fix the issue where the Client ID has not been provided. A separate issue will be created to handle the case where an invalid Client ID has been provided.

For any questions or discussions, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[Discord](https://discord.gg/RTgxfFW9mS)

### PR DESCRIPTION
**Pull request by Sakshi-75**
## Associated Issue

Closes #51 

## Implemented Solution

I've added a new condition in case of error when anime list is not found due to invalid user to check if it's because the client ID has not been added and updated the error message for this scenario.

### CODE REVIEW

File: src/mya.c [hunk 1]
```diff
@@ -394,7 +394,10 @@ int main (int argc, char *argv[]) {
 
 		/* error when anime list is not found due to invalid user */
 		if (!json_object_object_get_ex(json, "data", &anime_list)) {
-			fprintf(stderr, "User not found\n");
+			if (strcmp(CLIENT_ID, "YOUR TOKEN HERE")==0)
```
Comment (jmakhack) [inline src/mya.c:397]: @Sakshi-75, can you add spaces around the `==` here? `HERE") == 0)`

Otherwise, all your changes look good!
Please ignore the Codacy Production warning.

Comment (Sakshi-75) [reply src/mya.c]: @jmakhack done!

**Review by jmakhack — APPROVED** [review]
Looks good, @Sakshi-75.

Thanks for contributing! :)

**Comment by jmakhack** [comment]
@all-contributors please add @Sakshi-75 for code
